### ISSUE TITLE
auto battle still freezee

### ISSUE THREAD

**Issue by luanon404** [ky-ler/StarRail-S-GC#4]
![image](https://github.com/ky-ler/StarRail-S-GC/assets/71830807/afe396ec-eafa-42e9-a3f3-1ff5359f783d)

Do you have any advice if you come across this?

**Comment by ky-ler** [comment]
I noticed that when a fight has multiple phases. I lower my speed to around 5 and that usually fixes it for me.

**Comment by luanon404** [comment]
> I noticed that when a fight has multiple phases. I lower my speed to around 5 and that usually fixes it for me.

my speed is 10.0f, so speed so fast cause cant get phases?

**Comment by luanon404** [comment]
so just set maximum is 5, 100 is to large

**Comment by ky-ler** [comment]
> so just set maximum is 5, 100 is to large

I set it to 10 earlier. https://github.com/ky-ler/StarRail-S-GC/commit/0238bd0826d00400ca5790c7814952a984d149b2

**Comment by luanon404** [comment]
> > so just set maximum is 5, 100 is to large
> 
> I set it to 10 earlier. [0238bd0](https://github.com/ky-ler/StarRail-S-GC/commit/0238bd0826d00400ca5790c7814952a984d149b2)

why not set it to 5, 10 still cause freeze

**Comment by ky-ler** [comment]
> 

only on battles with phases does it cause a freeze

**Comment by luanon404** [comment]
> only on battles with phases does it cause a freeze. you can still use 10 on battles without phases.

can u explain me what does phases mean?
