### ISSUE TITLE
use their dialog skip button

### ISSUE THREAD

**Issue by luanon404** [ky-ler/StarRail-S-GC#5]
![image](https://github.com/ky-ler/StarRail-S-GC/assets/71830807/e2a2b401-e9a3-432b-b47f-69dfa3642c0f)

only this dialog has this damn skip button.

**Comment by luanon404** [comment]
i think use their button better than spam capslook button

**Comment by ky-ler** [comment]
not every dialogue has that button

**Comment by luanon404** [comment]
> not every dialogue has that button

so cant? i mean if have then just use it instead.
